### ISSUE TITLE
What about.... Wordpress?

### ISSUE THREAD

**Issue by lightsoutinteractive** [jrpruit1/generator-lt-frontside#2]
Could we add this as an option in the bower components?

I could probably figure out how to do this after the initial install. I am working on that now, but just a though to maybe add this as an option upon install.

Also, how do we incorporate the live reload with PHP? I can run my MAMP as a different localhost and I think it will work, but I believe I would have to do live reloads for some things, but have to do a build to see it in action with the PHP.

**Comment by lightsoutinteractive** [comment]
@jrpruit1 

Here is probably a good example to get it done:
http://robandlauren.com/2014/02/05/live-reload-grunt-wordpress/

Looks like we will be working on this tomorrow. Really looking forward to it buddy!

**Comment by jakepruitt** [comment]
Yeah, for sure! Good time to kick the tires on the generator!

**Comment by jakepruitt** [comment]
@thedins since we're not working on this anymore, just going to close :+1:
